/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Block: typeof import('./src/components/global-setting/block.vue')['default']
    Chart: typeof import('./src/components/chart/index.vue')['default']
    FormWrapper: typeof import('./src/components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./src/components/global-setting/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
