/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/blog/album/': RouteRecordInfo<'/blog/album/', '/blog/album', Record<never, never>, Record<never, never>>,
    '/blog/article/': RouteRecordInfo<'/blog/article/', '/blog/article', Record<never, never>, Record<never, never>>,
    '/blog/category/': RouteRecordInfo<'/blog/category/', '/blog/category', Record<never, never>, Record<never, never>>,
    '/blog/friendLink/': RouteRecordInfo<'/blog/friendLink/', '/blog/friendLink', Record<never, never>, Record<never, never>>,
    '/blog/tag/': RouteRecordInfo<'/blog/tag/', '/blog/tag', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/': RouteRecordInfo<'/dashboard/monitor/', '/dashboard/monitor', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/components/chat-item': RouteRecordInfo<'/dashboard/monitor/components/chat-item', '/dashboard/monitor/components/chat-item', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/components/chat-list': RouteRecordInfo<'/dashboard/monitor/components/chat-list', '/dashboard/monitor/components/chat-list', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/components/chat-panel': RouteRecordInfo<'/dashboard/monitor/components/chat-panel', '/dashboard/monitor/components/chat-panel', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/components/data-statistic': RouteRecordInfo<'/dashboard/monitor/components/data-statistic', '/dashboard/monitor/components/data-statistic', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/components/data-statistic-list': RouteRecordInfo<'/dashboard/monitor/components/data-statistic-list', '/dashboard/monitor/components/data-statistic-list', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/components/quick-operation': RouteRecordInfo<'/dashboard/monitor/components/quick-operation', '/dashboard/monitor/components/quick-operation', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/components/studio': RouteRecordInfo<'/dashboard/monitor/components/studio', '/dashboard/monitor/components/studio', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/components/studio-information': RouteRecordInfo<'/dashboard/monitor/components/studio-information', '/dashboard/monitor/components/studio-information', Record<never, never>, Record<never, never>>,
    '/dashboard/monitor/components/studio-status': RouteRecordInfo<'/dashboard/monitor/components/studio-status', '/dashboard/monitor/components/studio-status', Record<never, never>, Record<never, never>>,
    '/dashboard/workplace/': RouteRecordInfo<'/dashboard/workplace/', '/dashboard/workplace', Record<never, never>, Record<never, never>>,
    '/dashboard/workplace/components/announcement': RouteRecordInfo<'/dashboard/workplace/components/announcement', '/dashboard/workplace/components/announcement', Record<never, never>, Record<never, never>>,
    '/dashboard/workplace/components/carousel': RouteRecordInfo<'/dashboard/workplace/components/carousel', '/dashboard/workplace/components/carousel', Record<never, never>, Record<never, never>>,
    '/dashboard/workplace/components/categories-percent': RouteRecordInfo<'/dashboard/workplace/components/categories-percent', '/dashboard/workplace/components/categories-percent', Record<never, never>, Record<never, never>>,
    '/dashboard/workplace/components/content-chart': RouteRecordInfo<'/dashboard/workplace/components/content-chart', '/dashboard/workplace/components/content-chart', Record<never, never>, Record<never, never>>,
    '/dashboard/workplace/components/data-panel': RouteRecordInfo<'/dashboard/workplace/components/data-panel', '/dashboard/workplace/components/data-panel', Record<never, never>, Record<never, never>>,
    '/dashboard/workplace/components/popular-content': RouteRecordInfo<'/dashboard/workplace/components/popular-content', '/dashboard/workplace/components/popular-content', Record<never, never>, Record<never, never>>,
    '/dashboard/workplace/components/quick-operation': RouteRecordInfo<'/dashboard/workplace/components/quick-operation', '/dashboard/workplace/components/quick-operation', Record<never, never>, Record<never, never>>,
    '/dashboard/workplace/components/recently-visited': RouteRecordInfo<'/dashboard/workplace/components/recently-visited', '/dashboard/workplace/components/recently-visited', Record<never, never>, Record<never, never>>,
    '/exception/403/': RouteRecordInfo<'/exception/403/', '/exception/403', Record<never, never>, Record<never, never>>,
    '/exception/404/': RouteRecordInfo<'/exception/404/', '/exception/404', Record<never, never>, Record<never, never>>,
    '/exception/500/': RouteRecordInfo<'/exception/500/', '/exception/500', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/login/components/login-form': RouteRecordInfo<'/login/components/login-form', '/login/components/login-form', Record<never, never>, Record<never, never>>,
    '/not-found/': RouteRecordInfo<'/not-found/', '/not-found', Record<never, never>, Record<never, never>>,
    '/redirect/': RouteRecordInfo<'/redirect/', '/redirect', Record<never, never>, Record<never, never>>,
  }
}
